// Mocks generated by Mockito 5.4.5 from annotations
// in blkwds_manager/test/widgets/dashboard/top_bar_summary_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:blkwds_manager/models/models.dart' as _i4;
import 'package:blkwds_manager/screens/dashboard/dashboard_controller.dart'
    as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DashboardController].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardController extends _i1.Mock
    implements _i3.DashboardController {
  MockDashboardController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set context(_i2.BuildContext? _context) => super.noSuchMethod(
    Invocation.setter(#context, _context),
    returnValueForMissingStub: null,
  );

  @override
  _i2.ValueNotifier<List<_i4.Gear>> get gearList =>
      (super.noSuchMethod(
            Invocation.getter(#gearList),
            returnValue: _FakeValueNotifier_0<List<_i4.Gear>>(
              this,
              Invocation.getter(#gearList),
            ),
          )
          as _i2.ValueNotifier<List<_i4.Gear>>);

  @override
  _i2.ValueNotifier<List<_i4.Member>> get memberList =>
      (super.noSuchMethod(
            Invocation.getter(#memberList),
            returnValue: _FakeValueNotifier_0<List<_i4.Member>>(
              this,
              Invocation.getter(#memberList),
            ),
          )
          as _i2.ValueNotifier<List<_i4.Member>>);

  @override
  _i2.ValueNotifier<List<_i4.Project>> get projectList =>
      (super.noSuchMethod(
            Invocation.getter(#projectList),
            returnValue: _FakeValueNotifier_0<List<_i4.Project>>(
              this,
              Invocation.getter(#projectList),
            ),
          )
          as _i2.ValueNotifier<List<_i4.Project>>);

  @override
  _i2.ValueNotifier<List<_i4.Booking>> get bookingList =>
      (super.noSuchMethod(
            Invocation.getter(#bookingList),
            returnValue: _FakeValueNotifier_0<List<_i4.Booking>>(
              this,
              Invocation.getter(#bookingList),
            ),
          )
          as _i2.ValueNotifier<List<_i4.Booking>>);

  @override
  _i2.ValueNotifier<List<_i4.Studio>> get studioList =>
      (super.noSuchMethod(
            Invocation.getter(#studioList),
            returnValue: _FakeValueNotifier_0<List<_i4.Studio>>(
              this,
              Invocation.getter(#studioList),
            ),
          )
          as _i2.ValueNotifier<List<_i4.Studio>>);

  @override
  _i2.ValueNotifier<List<_i4.ActivityLog>> get recentActivity =>
      (super.noSuchMethod(
            Invocation.getter(#recentActivity),
            returnValue: _FakeValueNotifier_0<List<_i4.ActivityLog>>(
              this,
              Invocation.getter(#recentActivity),
            ),
          )
          as _i2.ValueNotifier<List<_i4.ActivityLog>>);

  @override
  _i2.ValueNotifier<bool> get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#isLoading),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<String?> get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _FakeValueNotifier_0<String?>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as _i2.ValueNotifier<String?>);

  @override
  _i2.ValueNotifier<int> get gearOutCount =>
      (super.noSuchMethod(
            Invocation.getter(#gearOutCount),
            returnValue: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#gearOutCount),
            ),
          )
          as _i2.ValueNotifier<int>);

  @override
  _i2.ValueNotifier<int> get bookingsTodayCount =>
      (super.noSuchMethod(
            Invocation.getter(#bookingsTodayCount),
            returnValue: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#bookingsTodayCount),
            ),
          )
          as _i2.ValueNotifier<int>);

  @override
  _i2.ValueNotifier<int> get gearReturningCount =>
      (super.noSuchMethod(
            Invocation.getter(#gearReturningCount),
            returnValue: _FakeValueNotifier_0<int>(
              this,
              Invocation.getter(#gearReturningCount),
            ),
          )
          as _i2.ValueNotifier<int>);

  @override
  _i2.ValueNotifier<_i4.Booking?> get studioBookingToday =>
      (super.noSuchMethod(
            Invocation.getter(#studioBookingToday),
            returnValue: _FakeValueNotifier_0<_i4.Booking?>(
              this,
              Invocation.getter(#studioBookingToday),
            ),
          )
          as _i2.ValueNotifier<_i4.Booking?>);

  @override
  void setContext(_i2.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#setContext, [context]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> checkOutGear(
    _i4.Gear? gear,
    _i4.Member? member, {
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkOutGear, [gear, member], {#note: note}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkInGear(_i4.Gear? gear, {String? note}) =>
      (super.noSuchMethod(
            Invocation.method(#checkInGear, [gear], {#note: note}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  List<_i4.Gear> searchGear(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchGear, [query]),
            returnValue: <_i4.Gear>[],
          )
          as List<_i4.Gear>);

  @override
  List<_i4.Booking> getTodayBookings() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayBookings, []),
            returnValue: <_i4.Booking>[],
          )
          as List<_i4.Booking>);

  @override
  _i4.Studio? getStudioById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getStudioById, [id]))
          as _i4.Studio?);

  @override
  _i5.Future<void> refreshDashboardStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#refreshDashboardStatistics, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshEssentialData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshEssentialData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
