// Mocks generated by Mockito 5.4.5 from annotations
// in blkwds_manager/test/integration/gear_workflow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:blkwds_manager/services/contextual_error_handler.dart' as _i4;
import 'package:blkwds_manager/services/db_service.dart' as _i2;
import 'package:blkwds_manager/services/error_service.dart' as _i3;
import 'package:blkwds_manager/services/snackbar_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DBService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBService extends _i1.Mock implements _i2.DBService {
  MockDBService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ErrorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorService extends _i1.Mock implements _i3.ErrorService {
  MockErrorService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ContextualErrorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextualErrorHandler extends _i1.Mock
    implements _i4.ContextualErrorHandler {
  MockContextualErrorHandler() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [SnackbarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnackbarService extends _i1.Mock implements _i5.SnackbarService {
  MockSnackbarService() {
    _i1.throwOnMissingStub(this);
  }
}
